name: Storybook

on:
  push:
    branches:
      - main
      - wzulfikar/gh-action-change-yarn-to-pnpm
    # paths:
    #   - "src/components/**/*.ts"
    #   - "src/components/**/*.tsx"

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          # pnpm cache files are stored in `~/.pnpm-store` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
          restore-keys: |
            {{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --silent --frozen-lockfile

      - name: Run typechecking
        run: pnpm tsc --noemit

      - name: Run tests
        run: pnpm test

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static
